namespace OpenHab.App.Localization;

public static class DefaultEnglishTextLocalizer
{
    private static readonly IReadOnlyDictionary<string, string> Strings = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["App.Name"] = "openHAB",
        ["Common.Cancel"] = "Cancel",
        ["Common.Clear"] = "Clear",
        ["Common.Continue"] = "Continue",
        ["Common.Delete"] = "Delete",
        ["Common.Edit"] = "Edit",
        ["Common.Reset"] = "Reset",
        ["Common.Save"] = "Save",
        ["Notifications.DefaultTitle"] = "openHAB",
        ["Notifications.Empty.NoMatches"] = "No matching notifications",
        ["Notifications.Empty.NoUnread"] = "No unread notifications",
        ["Notifications.Empty.NoRead"] = "No read notifications",
        ["Notifications.Empty.NoHidden"] = "No hidden notifications",
        ["Notifications.Empty.NoNotifications"] = "No notifications",
        ["Notifications.MarkUnread"] = "Mark unread",
        ["Notifications.MarkRead"] = "Mark read",
        ["Notifications.Unhide"] = "Unhide",
        ["Notifications.Hide"] = "Hide",
        ["Notifications.Elapsed.JustNow"] = "Just now",
        ["Notifications.Elapsed.MinutesAgo"] = "{0}m ago",
        ["Notifications.Elapsed.HoursAgo"] = "{0}h ago",
        ["Notifications.Elapsed.DaysAgo"] = "{0}d ago",
        ["Tray.OpenFlyout"] = "Open flyout",
        ["Tray.OpenMainWindow"] = "Open main window",
        ["Tray.Exit"] = "Exit",
        ["Settings.Title"] = "Settings",
        ["Settings.Root.Subtitle"] = "Choose a category",
        ["Settings.Connection.Title"] = "Connection",
        ["Settings.Connection.Subtitle"] = "Endpoints and credentials",
        ["Settings.General.Title"] = "General",
        ["Settings.General.Subtitle"] = "Startup, flyout width, notifications",
        ["Settings.General.PageSubtitle"] = "Startup and runtime behavior",
        ["Settings.Appearance.Title"] = "Appearance",
        ["Settings.Appearance.Subtitle"] = "Skin, theme, icon style",
        ["Settings.Appearance.PageSubtitle"] = "Visual options",
        ["Settings.DeviceInfoSync.Title"] = "Device Info Sync",
        ["Settings.DeviceInfoSync.Subtitle"] = "Configure device metadata sync",
        ["Settings.Shortcuts.Title"] = "Shortcuts",
        ["Settings.Shortcuts.Subtitle"] = "Command menu and global shortcuts",
        ["Settings.Shortcuts.PageSubtitle"] = "Configure global shortcuts and command menu actions.",
        ["Settings.About.Title"] = "About",
        ["Settings.About.Subtitle"] = "Logs and version",
        ["Runtime.Status.Loading"] = "Loading...",
        ["Runtime.Connection.Failed"] = "Connection failed.",
        ["Runtime.Connection.FallbackFailed"] = "Fallback failed.",
        ["Runtime.Connection.ConnectedViaCloudLocalFailed"] = "Connected via cloud (local failed).",
        ["Runtime.Connection.ConnectedViaCloud"] = "Connected via cloud ({0})",
        ["Runtime.Connection.ConnectedViaLocal"] = "Connected via local ({0})",
        ["Runtime.Connection.State"] = "Connection: {0}",
        ["Runtime.LiveUpdates.UnavailableRefreshManually"] = "Live updates unavailable. Refresh manually.",
        ["Runtime.MainUi.LoadError"] = "Error: Main UI could not be loaded.",
        ["Runtime.Error"] = "Error.",
        ["Sitemap.Search.ResultsTitle"] = "Search results",
        ["Sitemap.Action.Run"] = "Run",
        ["Sitemap.WebView.NoUrlConfigured"] = "No URL configured",
        ["Sitemap.WebView.OpenInBrowser"] = "Open in browser",
        ["Sitemap.Chart.RequiresItem"] = "Chart requires an item",
        ["Shortcuts.Validation.TargetItemRequired"] = "Target Item is required.",
        ["Shortcuts.Validation.CommandValueRequired"] = "Command value is required for this action type.",
        ["Shortcuts.Validation.BindingAlreadyUsed"] = "Shortcut is already used by {0}.",
        ["Shortcuts.CommandMenu.OwnerName"] = "openHAB Command Menu",
        ["Shortcuts.ActionOwner"] = "Action: {0}",
        ["Shortcuts.UnnamedAction"] = "Unnamed action",
        ["ShortcutRecorder.Dialog.Title"] = "Activation shortcut",
        ["ShortcutRecorder.EditShortcut"] = "Edit shortcut",
        ["ShortcutRecorder.ClearShortcut"] = "Clear shortcut",
        ["ShortcutRecorder.PressModifierAndKey"] = "Press a modifier and key.",
        ["ShortcutRecorder.RequiresModifier"] = "Shortcut must start with Windows, Ctrl, Alt, or Shift.",
        ["ShortcutRecorder.ResetToCurrent"] = "Reset to current shortcut.",
        ["ShortcutRecorder.ShortcutCleared"] = "Shortcut cleared.",
        ["ShortcutRecorder.ShortcutRequiredForControl"] = "Shortcut is required for this control.",
        ["ShortcutRecorder.ShortcutRequired"] = "Shortcut is required.",
        ["ShortcutRecorder.UnsupportedKey"] = "Unsupported key.",
        ["ShortcutRecorder.UseAtLeastOneModifier"] = "Use at least one modifier key."
    };

    public static ITextLocalizer Instance { get; } = new InvariantTextLocalizer(Strings);
}
